### ISSUE TITLE
rpath needs to be patched

### ISSUE THREAD

**Issue by probonopd** [anupam-git/vlc-appimage#3]
`rpath` needs to be patched in each executable and library, where it is currently pointing to the non-existing absolute location `/home/anupam/vlc-3.0.0/build/lib`. For example:

```
patchelf --print-rpath usr/lib/vlc/plugins/gui/libqt_plugin.so
/home/anupam/vlc-3.0.0/build/lib

patchelf --print-rpath usr/bin/vlc
/home/anupam/vlc-3.0.0/build/lib
```

They all need to be patched with `patchelf --set-rpath ...` to a relative path starting with `$ORIGIN` (the directory of the file itself), e.g., `patchelf --set-rpath '$ORIGIN/../../lib' usr/bin/vlc` would make it look in `lib/` for libraries.

**Comment by anupam-git** [comment]
@probonopd Thanks for your suggestions..
Made the fixes and pushed the updated appimage in [Releases](https://github.com/anupam-git/vlc-appimage/releases/tag/3.0.0). Can you please test it once ?

**Comment by probonopd** [comment]
Thanks @anupam-git - VLC launches the GUI now. Progress!
However, I can't seem to play, e.g., https://www.youtube.com/watch?v=ROyRtqKBzDk - does it work for you?

**Comment by anupam-git** [comment]
@probonopd Tried playing on live 16.04.. Did not play.. Might be due to unavailability of codecs..
Played fine in my installed ubuntu 16.04..

**Comment by probonopd** [comment]
Then we should bundle the codecs as well...

**Comment by anupam-git** [comment]
Looking into it..
Closing this issue as it is fixed. Opening a new issue..
